CREATE TABLE author(
    id SERIAL PRIMARY KEY ,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    access INT DEFAULT 0

)